h1[0]="A"
h1[image]="kathara/base"

h2[0]="A"
h2[image]="kathara/base"

h3[0]="A/02:04:06:11:22:33"    #fixed MAC Address
h3[image]="kathara/base"

dhcp[0]="A"
dhcp[image]="kathara/dhcp"    #custom image

# to check traffic (optional)
wireshark[bridged]=true
wireshark[port]="3000:3000/tcp"
wireshark[image]="lscr.io/linuxserver/wireshark"
wireshark[num_terms]=0
