www[0]="A"
www[image]="kathara/base"

ftp[0]="A"
ftp[image]="kathara/base"

local1[0]="B"
local1[image]="kathara/base"

local2[0]="B"
local2[image]="kathara/base"

remote1[0]="C"
remote1[image]="kathara/base"

google[0]="C"
google[image]="kathara/base"

# device that will do the firewalling
firewall[0]="A"
firewall[1]="B"
firewall[2]="C"
firewall[image]="kathara/base"
