alice[0]="A"	#MAC Address ALice
alice[image]="kathara/base"

bob[0]="A/b0:bb:0b:b0:bb:0b"	#MAC Address Bob
bob[image]="kathara/base"

eve[0]="A/ba:de:7e:ba:de:7e"	#MAC Address Eve
eve[image]="kathara/ettercap"
eve[sysctl]="net.ipv6.conf.all.forwarding=1"

# to check traffic
wireshark[bridged]=true
wireshark[port]="3000:3000/tcp"
wireshark[image]="lscr.io/linuxserver/wireshark"
wireshark[num_terms]=0
