port=53
no-resolv

#DNS settings
server=8.8.8.8

# DHCP settings
interface=eth0
dhcp-authoritative

# dhcp range LAN1 (min-max IP), lease time + gw default
dhcp-range=LAN1,192.168.1.10,192.168.1.19,255.255.255.0,1h
dhcp-option=LAN1,3,192.168.1.254

# dhcp range LAN2 (min-max IP), lease time + gw default
dhcp-range=LAN2,192.168.2.20,192.168.2.29,255.255.255.0,1h
dhcp-option=LAN2,3,192.168.2.254

# dhcp range LAN3 (min-max IP), lease time + gw default
dhcp-range=LAN3,192.168.3.30,192.168.3.39,255.255.255.0,1h
dhcp-option=LAN3,3,192.168.3.254


